pipeline {
    agent any

    stages {

        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Verify Environment'){
            steps{
                sh 'java -version'
                sh 'mvn -version'
                sh 'docker --version'
            }
        }

        stage('Test'){
            steps{
                dir('driverservice'){
                    withCredentials([
                        string(
                            credentialsId: 'ridehub_driver_db-url',
                            variable: 'DB_URL'
                        ),
                        usernamePassword(
                            credentialsId: 'ridehub-db',
                            usernameVariable: 'DB_USERNAME',
                            passwordVariable: 'DB_PASSWORD'
                        )
                    ]){
                        sh 'mvn clean test'
                    }
                }
            }
        }

        stage('build'){
            steps{
                dir('driverservice'){
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Docker Build'){
            steps{
                dir('driverservice'){
                    sh 'docker build -t ridehub-driver-service:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Push to ECR') {
                    steps {
                        dir('driverservice') {
                            withCredentials([
                                [$class: 'AmazonWebServicesCredentialsBinding',
                                 credentialsId: 'aws-ecr']
                            ]) {
                                sh '''
                                    AWS_REGION="ap-south-2"
                                    AWS_ACCOUNT_ID="115628507548"
                                    ECR_REPOSITORY="ridehub-app-deploy-admin"

                                    ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

                                    ECR_IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:ridehub-driver-service-$BUILD_NUMBER"

                                    echo "Logging in to Amazon ECR..."

                                    aws ecr get-login-password --region "$AWS_REGION" | \
                                    docker login --username AWS --password-stdin "$ECR_REGISTRY"

                                    echo "Tagging Docker image..."

                                    docker tag \
                                    "ridehub-driver-service:$BUILD_NUMBER" \
                                    "$ECR_IMAGE"

                                    echo "Pushing Docker image to ECR..."

                                    docker push "$ECR_IMAGE"

                                    echo "Successfully pushed: $ECR_IMAGE"
                                '''
                            }
                        }
                    }
                }
    }

    post {
        success {
            echo 'Tests and build completed successfully!'
        }
        failure{
            echo 'Pipeline failed. Check the jenkins console output'
        }
    }
}